# ABOUTME: Conventional commit format checker for all PR commits
name: Conventional Commit Check

on:
  pull_request:
    branches: [master]

jobs:
  check-commit-format:
    uses: maxrantil/.github/.github/workflows/conventional-commit-check-reusable.yml@master
    with:
      allowed-types: 'feat,fix,docs,style,refactor,test,chore,perf,ci,build,revert'
      base-branch: 'master'
